export type ApiErrorCode =
  | "INTERNAL_ERROR"
  | "NOT_FOUND"
  | "SERVICE_UNAVAILABLE"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "VALIDATION_ERROR"
  | "EMAIL_NOT_VERIFIED"
  | "INVALID_CREDENTIALS"
  | "INVITATION_INVALID"
  | "INVITATION_EXPIRED"
  | "INVITATION_ALREADY_USED"
  | "WORKSPACE_NOT_FOUND"
  | "CHANNEL_NOT_FOUND"
  | "CHANNEL_NAME_TAKEN"
  | "DEFAULT_CHANNEL_PROTECTED"
  | "MESSAGE_NOT_FOUND"
  | "MESSAGE_EMPTY"
  | "MESSAGE_TOO_LONG"
  | "CHANNEL_ARCHIVED"
  | "INVALID_CURSOR"
  | "MESSAGE_SEND_RATE_LIMITED"
  | "RATE_LIMITED";

export interface ApiErrorResponse {
  error: {
    code: ApiErrorCode;
    message: string;
    requestId?: string;
  };
}
